# Generated by Django 3.0.2 on 2020-02-04 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'prefecture',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_kana', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('address1', models.CharField(db_index=True, max_length=255)),
                ('address2', models.CharField(db_index=True, max_length=255)),
                ('url', models.CharField(max_length=1024)),
                ('tel', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField()),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Prefecture')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.CharField(db_index=True, max_length=7, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Prefecture')),
            ],
            options={
                'db_table': 'zip_code',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
            options={
                'db_table': 'shop_image',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Zipcode'),
        ),
    ]
