# Generated by Django 3.0.2 on 2020-02-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address1',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address2',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name_kana',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prefecture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Prefecture'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='zip_code',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Zipcode'),
        ),
    ]
