# Generated by Django 3.0.3 on 2020-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20200210_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopimage',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
